name: YouTube Reply Check

on:
  workflow_dispatch:  # 手動実行を可能にするトリガー

jobs:
  reply-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install google-api-python-client

      - name: Run script
        run: python youtube_reply_check.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
        
