name: YouTube Auto Reply

on:
  workflow_dispatch:

jobs:
  youtube-auto-reply:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-auth google-api-python-client

    - name: Set Service Account JSON
      run: echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" > service_account.json

    - name: Run Auto Reply Script
      env:
        SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      run: python youtube_auto_reply.py
